"""Tool requirements used to describe capabilities across diagnostic scopes."""

CAPABILITY_TOOLS: dict[str, frozenset[str]] = {
    "files": frozenset({"files_read", "files_write"}),
    "terminal": frozenset({"terminal_start", "terminal_output", "terminal_input",
                            "terminal_list", "terminal_stop"}),
    "browser_isolated": frozenset({"browser_open", "browser_navigate", "browser_observe",
                                    "browser_source", "browser_network", "browser_research",
                                    "browser_click",
                                    "browser_fill", "browser_key", "browser_drag",
                                    "browser_file_upload", "browser_download", "browser_close"}),
    "literal_search": frozenset({"search_start", "search_results", "search_list",
                                  "search_stop"}),
    "office_text_read": frozenset({"documents_read"}),
    "office_rendered_preview": frozenset({"documents_preview"}),
    "audio_capture": frozenset({"audio_status", "audio_capture"}),
    "media_preview": frozenset({"media_status", "media_audio_clip",
                                "media_video_frames"}),
    "gui_native": frozenset({"gui_native_windows", "gui_native_observe", "gui_native_close",
                             "gui_native_set_value", "gui_native_press",
                             "gui_native_set_value_target", "gui_native_press_target"}),
    "gui_mcp": frozenset({"gui_observe", "gui_click", "gui_type", "gui_key"}),
    "skills": frozenset({"skills_list", "skills_read"}),
    "codex_skills": frozenset({"codex_skills_list", "codex_skill_read"}),
}
